version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - DATABASE_HOST= 127.0.0.1
      - POSTGRES_DB=my_store
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql:
     image: mysql
     restart: always
     environment:
       MYSQL_DATABASE: my_store_2
       MYSQL_ROOT_PASSWORD: admin1234
       MYSQL_PORT: 3306
     ports:
       - "3306:3306"
     volumes:
       - mysql-data:/var/lib/mysql

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
       - MYSQL_ROOT_PASSWORD=admin1234
       - PMA_HOST=mysql
     ports:
       - "8000:80"

volumes:
  mysql-data:
    external: true
